const AT = {
  SET_TEXT_SYNC: 'SET_TEXT_SYNC',
  SET_TEXT_ASYNC: 'SET_TEXT_ASYNC',
  SET_TEXT_ASYNC_SUCCESS: 'SET_TEXT_ASYNC_SUCCESS',
  SET_TEXT_ASYNC_FAIL: 'SET_TEXT_ASYNC_FAIL',
  GET_TOP_RATED_SUCCESS: 'GET_TOP_RATED_SUCCESS',
  GET_POPULAR_SUCCESS: 'GET_POPULAR_SUCCESS',
  GET_UPCOMING_SUCCESS: 'GET_UPCOMING_SUCCESS'
};

export default AT;
